---
title: "Term similarity"
author: "Zuguang Gu ( z.gu@dkfz.de )"
date: '`r Sys.Date()`'
output: html_document
vignette: >
  %\VignetteIndexEntry{4. Term similarity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align = "center")
```

<style>
body h1 {
    text-decoration: underline;
}
</style>


## Denotations

The following denotations will be used throughout the vignette.

|  Denotation |  Description    |
| :----- | :------------------------ |
| $r$ | The root term of the DAG.  |
| $\delta(x)$ | The depth of a term $x$ in the DAG, which is the longest distance from root $r$. |
| $\delta_s(x)$ | The length of the longest path from root $r$ to a term $x$ via term $s$. |
| $\delta_\max$ | The maximal depth in the DAG. |
| $\eta(x)$ | The height of term $x$ in the DAG, which is the longest finite distance to leaf terms. |
| $\mathcal{C}_s$ | The set of child terms of term $s$. |
| $\mathcal{P}_s$ | The set of parents terms of term $s$. |
| $\mathcal{A}_s$ | The set of ancestor terms of term $s$. |
| $\mathcal{A}_s^+$ | The set of ancestor terms of term $s$, including $s$ itself. |
| $\mathcal{D}_s$ | The set of offspring terms of term $s$. |
| $\mathcal{D}_s^+$ | The set of offspring terms of term $s$, including $s$ itself. |
| $\mathcal{L}_s$ | The set of leaf terms that term $s$ can reach. |
| $\left| A \right|$ | Number of elements in set $A$. |
| $D_\mathrm{sp}(a, b)$ | The shortest distance bewteen $a$ and $b$. | 
| $\mathrm{len}(a, b)$ | The longest distance bewteen $a$ and $b$. |
| $\mathrm{len}_s(a, b)$ | The length of the longest path from $a$ and $b$ via $s$. |
| $\mathrm{CA}(a, b)$ | The set of common ancestors of term $a$ and $b$, i.e. $\mathrm{CA}(a, b) = \mathcal{A}_a^+ \bigcap \mathcal{A}_b^+$ |
| $\mathrm{LCA}(a, b)$ | Lowest common ancestor of $a$ and $b$, which is the common ancestor with the highest depth in DAG, i.e. $$\operatorname*{argmax}_{t \in \mathrm{CA}(a, b)} \delta(t)$$ There might be more than one LCA terms for given two terms, the one with the smallest distance to $a$ and $b$ is used. |
| $\mathrm{NCA}(a, b)$ | Nearest common ancestor of $a$ and $b$, i.e. $$\operatorname*{argmin}_{t \in \mathrm{CA}(a, b)} \left( D_\mathrm{sp}(t, a) + D_\mathrm{sp}(t, b) \right)$$. If there are more than one NCA terms, the one with the highest depth is used. |
| $\mathrm{MICA}(a, b)$ | Most informative common ancestor of $a$ and $b$, i.e. $$\operatorname*{argmax}_{t \in \mathrm{CA}(a, b)} \left( \mathrm{IC}(t) \right )$$. There might be more than one MICA terms for given two terms, the one with the smallest distance to $a$ and $b$ is used.|
| $G_s$ | The set of annotated items on term $s$. |


The function `term_sim()` calculates semantic similarities for a group of terms.

```r
term_sim(dag, terms, method = ...)
```

# IC-based or node-based methods

This type of methods considers a special ancestor term $c$ of terms $a$ and
$b$, which has the highest IC among all $a$ and $b$'s ancestor terms. Term $c$
is called the most informative common ancestor (MICA) which can be given by:

$$ \mathrm{IC}(c) = \max_{x \in \mathcal{A}_a^+ \cap \mathcal{A}_b^+} \mathrm{IC}(x)  $$

So if two terms are identical, MICA is the term itself, and if two terms have
ancestor/offspring relationship, MICA is the ancestor term.

In the following sections, if not specially mentioned, $c$ is always referred
to the MICA of $a$ and $b$.

## Sim_Lin_1998

The similarity is calculated as the IC of the MICA term $c$ normalized by the
average of the IC of the two terms:

$$ \mathrm{Sim}(a, b) = \frac{\mathrm{IC}(c)}{(\mathrm{IC}(a) + \mathrm{IC}(b))/2} = \frac{2 * \mathrm{IC}(c)}{\mathrm{IC}(a) + \mathrm{IC}(b)} $$


```r
term_sim(dag, terms, method = "Sim_Lin_1998")
```

Paper link: https://dl.acm.org/doi/10.5555/645527.657297.


## Sim_Resnik_1999

IC of the MICA term itself ($\mathrm{IC}(c)$) can be a measure of how similar
two terms are, but its range is not in `[0, 1]`. There are several ways to
normalize $\mathrm{IC}(c)$ in the range of `[0, 1]`. Note some of the
normalize is restricted to _IC_annotation_ as the IC method.

### Nunif

It is normalized to the possible maximal IC value where a term only has one
item annotated.

$$ \mathrm{Sim}(a, b) = \frac{\mathrm{IC}(c)}{-\log(1/N)} = \frac{\mathrm{IC}(c)}{\log N} $$


where $N$ is the total number of items annotated to the whole DAG.

### Nmax

It is similar as _Nunif_, but normalized to the maximal IC of all terms in the
DAG. If there is a term with only one item annotated, _Nmax_ is identical to
the _Nunif_ method.

$$ \mathrm{Sim}(a, b) = \frac{\mathrm{IC}(c)}{\mathrm{IC}_\mathrm{max}} $$


### Nunivers

$\mathrm{IC}(c)$ is normalized by the maximal IC of term $a$ and $b$.

$$ \mathrm{Sim}(a, b) = \frac{\mathrm{IC}(c)}{\max \{ \mathrm{IC}(a), \mathrm{IC}(b) \}} $$

Paper link: https://doi.org/10.1613/jair.514, https://doi.org/10.1186/1471-2105-9-S5-S4, https://doi.org/10.1186/1471-2105-11-562, https://doi.org/10.1155/2013/292063.


The normalization method can be set with the norm_method parameter:

```r
term_sim(dag, terms, method = "Sim_Resnik_1999",
    control = list(norm_method = "Nmax"))
```

Possible values for the norm_method parameter are "Nunif", "Nmax", "Nunivers"
and "none".

## Sim_FaITH_2010

It is calculated as:

$$ \mathrm{Sim}(a, b) = \frac{\mathrm{IC}(c)}{\mathrm{IC}(a) + \mathrm{IC}(b) - \mathrm{IC}(c)} $$


The relation between the _FaITH_2010_ similarity and _Lin_1998_ similarity is:

$$ \mathrm{Sim}_\mathrm{FaITH} = \frac{\mathrm{Sim}_\mathrm{Lin}}{2 - \mathrm{Sim}_\mathrm{Lin}} $$


```r
term_sim(dag, terms, method = "Sim_FaITH_2010")
```

Paper link: https://doi.org/10.1007/978-3-642-17746-0_39.

## Sim_Relevance_2006

The IC method is fixed to _IC_annotation_.

If thinking _Lin_1998_ is a measure of how close term $a$ and $b$ to their
MICA $c$, the relevance method corrects it by multiplying a factor which
considers the specificity of how $c$ brings the information. The factor is
calculated as $1-p(c)$ where $p(c)$ is the annotation-based probability $p(c)
= k/N$ where $k$ is the number of items annotated to $c$ and $N$ is the total
number of items annotated to the DAG. Then under the Relevance method, the
corrected IC of $c$ is:

$$ \mathrm{IC}_\mathrm{corrected}(c) = (1-p(c)) * \mathrm{IC}(c) $$

If using _Lin_1998_ as the similarity method, the corrected version Relevance
similarity is:

$$ 
\begin{align*}
\mathrm{Sim}(a, b) & = \frac{2*\mathrm{IC}_\mathrm{corrected}(c)}{\mathrm{IC}(a) + \mathrm{IC}(b)} \\
                   & = (1-p(c)) * \frac{2 * \mathrm{IC}(c)}{\mathrm{IC}(a) + \mathrm{IC}(b)} \\
                   & = (1-p(c)) * \mathrm{Sim}_\mathrm{Lin}(a, b)
\end{align*} $$


```r
term_sim(dag, terms, method = "Sim_Relevance_2006")
```

Paper link: https://doi.org/10.1186/1471-2105-7-302

## Sim_SimIC_2010

The IC method is fixed to _IC_annotation_.

The SimIC method is an improved correction method of the Relevance method
because the latter works bad when $p(c)$ is very small, because when $1-p(c)$
is used as a correction factor, it cannot nicely distinguish e.g. when $p(c) = 0.01$ and $p(c) = 0.001$.

The SimIC correction factor for MICA term c is:


$$ \mathrm{IC}_\mathrm{corrected}(c) = \frac{\log(p(c))}{1 - \log(p(c))} * \mathrm{IC}(c) $$


Then the similarity is:

$$ \mathrm{Sim}(a, b) = \frac{\log(p(c))}{1 - \log(p(c))} * \mathrm{Sim}_\mathrm{Lin}(a, b) $$


```r
term_sim(dag, terms, method = "Sim_SimIC_2010")
```

Paper link: https://doi.org/10.48550/arXiv.1001.0958.


## Sim_XGraSM_2013

The IC method is fixed to _IC_annotation_.

Being different from the "Relevance" and "SimIC_2010" methods that only use
the IC of the MICA term, the _XGraSM_2013_ as well as the next two methods use
IC of a subset of common ancestor terms of $a$ and $b$, and it uses the mean
IC of them. The subset of common ancestor may have different names for
different methods.

_XGraSM_2013_ is the simplest one which uses informative common ancestors
(ICA) where IC of the common ancestor should be non-zero.

$$ \mathrm{ICA}(a, b) = \{c \in \mathcal{A}_a^+ \cap \mathcal{A}_b^+: \mathrm{IC}(c) > 0\} $$

And mean IC among all ICA terms:

$$ \mathrm{IC}_\mathrm{mean} = \frac{1}{|\mathrm{ICA}(a, b)|} \sum_{\mathrm{t \in \mathrm{ICA}(a, b)}} \mathrm{IC}(t) $$

And applying _Lin_1998_ method, the semantic similarit is:

$$ \mathrm{Sim}(a, b) = 2 * \frac{\mathrm{IC}_\mathrm{mean}}{\mathrm{IC}(a) + \mathrm{IC}(b)} $$

```r
term_sim(dag, terms, method = "Sim_XGraSM_2013")
```

Paper link: https://doi.org/10.1186/1471-2105-14-284

## Sim_GraSM_2005

The IC method is fixed to _IC_annotation_.

It applies a complicate way to selet a subset of common ancestors of terms $a$
and $b$. The main idea is that information transmission from ancestors to a
term may overlap and it aims to find paths from upstream that give exclusive
transmissions.

First, for a term $x$ define its disjunctive ancestors (DA) pairs $s$ and $t$
where there exists a path from $s$ to $x$ which does not pass $t$, and at the
same time there also exists a path from $t$ to $x$ which does not pass $s$. In
other words, the directed distance between $s$ and $t$ is zero. In this way,
the two $\mathrm{DA}(x)$ terms can transmit exclusive information to $x$.

Next, for every common ancestor $c$ of term $a$ and $b$, $c$ is only selected
if there is another common ancestor $c'$ which have smaller IC than $c$
($\mathrm{IC}(c) > \mathrm{IC}(c')$), the pair $(c, c')$ is the DA of either
$a$ or $b$. The set of selected common ancestors is called the disjunctive
common ancestor (DCA).

And mean IC among all DCA terms:

$$ \mathrm{IC}_\mathrm{mean} = \frac{1}{|\mathrm{DCA}(a, b)|} \sum_{\mathrm{t \in \mathrm{DCA}(a, b)}} \mathrm{IC}(t) $$

And applying _Lin_1998_ method, the semantic similarit is:

$$ \mathrm{Sim}(a, b) = 2 * \frac{\mathrm{IC}_\mathrm{mean}}{\mathrm{IC}(a) + \mathrm{IC}(b)} $$

```r
term_sim(dag, terms, method = "Sim_GraSM_2005")
```

Paper link: https://doi.org/10.1145/1099554.1099658.

## Sim_EISI_2015

The IC method is fixed to _IC_annotation_.

It also selects a specific subset of common ancestors of terms $a$ and $b$. It
only selects a common ancestor $c$ which can reach $a$ or $b$ via one of its
child terms that does not belong to the common ancestors (mutual exclusively
in $a$'s ancestors or in $b$'s ancestors). The set of the selected common
ancestors is called the exclusively inherited common ancestors (EICA).

$$ \mathrm{EICA}(a, b) = \{c \in \mathcal{A}_a \cap \mathcal{A}_b: \mathcal{C}_c \cap \left( (\mathcal{A}_a \cup \mathcal{A}_b) - (\mathcal{A}_a \cap \mathcal{A}_b) \neq \o \right) \}  $$

And mean IC among all EICA terms:

$$ \mathrm{IC}_\mathrm{mean} = \frac{1}{|\mathrm{EICA}(a, b)|} \sum_{\mathrm{t \in \mathrm{EICA}(a, b)}} \mathrm{IC}(t) $$

And applying _Lin_1998_ method, the semantic similarit is:

$$ \mathrm{Sim}(a, b) = 2 * \frac{\mathrm{IC}_\mathrm{mean}}{\mathrm{IC}(a) + \mathrm{IC}(b)} $$

```r
term_sim(dag, terms, method = "Sim_EISI_2015")
```

Paper link: https://doi.org/10.1016/j.gene.2014.12.062

## Sim_AIC_2014

It uses the aggregate information content from ancestors. First define the
semantic weight denoted as $S_w$ of a term $t$ in the DAG:


$$ S_w(t) = \frac{1}{1 + \exp \left(-\frac{1}{\mathrm{IC}(t)} \right)} $$

Then the similarity is calculated as the fraction of aggegation from common
ancestors and the average aggregation of ancestors for $a$ and $b$ separately.

$$ \mathrm{Sim}(a, b) = \frac{2*\sum\limits_{t \in \mathcal{A}_a^+ \cap \mathcal{A}_b^+} S_w(t) }{ \sum\limits_{t \in \mathcal{A}_a^+} S_w(t) + \sum\limits_{t \in \mathcal{A}_b^+} S_w(t) }  $$

```r
term_sim(dag, terms, method = "Sim_AIC_2014")
```

Paper link: https://doi.org/10.1109/tcbb.2013.176.

## Sim_Zhang_2006

It uses the _IC_Zhang_2006_ IC method and uses _Lin_1998_ form method to calculate similarities:

$$ \mathrm{Sim}(a, b) = \frac{2*\mathrm{IC}_\mathrm{Zhang}(c)}{\mathrm{IC}_\mathrm{Zhang}(a) + \mathrm{IC}_\mathrm{Zhang}(b)} $$

```r
term_sim(dag, terms, method = "Sim_Zhang_2006")
```


## Sim_universal

It uses the _IC_universal_ IC method and uses the _Nunivers_ method to calculate similarities:

$$ \mathrm{Sim}(a, b) = \frac{2*\mathrm{IC}_\mathrm{Univers}(c)}{\max \{ \mathrm{IC}_\mathrm{Univers}(a), \mathrm{IC}_\mathrm{Univers}(b) \}} $$

```r
term_sim(dag, terms, method = "Sim_universal")
```


## Sim_Wang_2007

Similar as the _Sim_AIC_2014_ method, it is also aggregation from ancestors, but it uses the "S-value"
introduced in the IC_Wang sectionn in xx.

$$ \mathrm{Sim}(a, b) = \frac{\sum\limits_{t \in \mathcal{A}_a^+ \cap \mathcal{A}_b^+} (S_a(t) + S_b(t)) }{ \sum\limits_{t \in \mathcal{A}_a^+} S_a(t) + \sum\limits_{t \in \mathcal{A}_b^+} S_b(t) }  $$


The contribution of different semantic relations can be set with the
`contribution_factor` parameter. The value should be a named numeric vector
where names should cover the relations defined in relations set in
`create_ontology_DAG()`. For example, if there are two relations "relation_a"
and "relation_b" set in the DAG, the value for contribution_factor can be set
as:

```r
term_sim(dag, terms, method = "Sim_Wang_2007", 
    control = list(contribution_factor = c("relation_a" = 0.8, "relation_b" = 0.6)))
```

By default 0.8 is set for "is_a" and 0.6 for "part_of".

If you are not sure what types of relations have been set, simply type the `dag` object.
The relation types will be printed there.

Paper link: https://doi.org/10.1093/bioinformatics/btm087.


# Edge-based methods

Methods introduced in this section replies on the distance between terms. Many methods are defined
originally based on the shortest distance between two terms. This section extends them to also
support longest distance via the LCA term.

## Sim_Rada_1989

It is based on the distance between term $a$ and $b$. It is defined as:

$$ \mathrm{Sim}(a, b) = \frac{1}{1 + D_\mathrm{sp}(a, b)} $$

which is based on the shortest distance between $a$ and $b$. Optionally,
the distance can also be the longest distance via the LCA term $c$.

$$ \mathrm{Sim}(a, b) = \frac{1}{1 + \mathrm{len}_c(a, b)} $$

There is a parameter distance which takes value of "longest_distances_via_LCA"
(the default) or "shortest_distances_via_NCA":

```r
term_sim(dag, terms, method = "Sim_Rada_1989",
    control = list(distance = "shortest_distances_via_NCA"))
```

Paper link: https://doi.org/10.1109/21.24528.


## Sim_Resnik_edge_2005

It is a normalized distance:

$$ \mathrm{Sim}(a, b) = 1 - \frac{D_\mathrm{sp}(a, b)}{2*\delta_\mathrm{max}} $$

where $2*\delta_\mathrm{max}$ can be thought as the possible maximal distance
between two terms in the DAG.

Similarly, the distance can also be the longest distance via LCA, then it is
consistent with the definition of $\delta_\mathrm{max}$ which are both based
on the longest distance.

$$ \mathrm{Sim}(a, b) = 1 - \frac{\mathrm{len}_c(a, b)}{2*\delta_\mathrm{max}} $$


There is a parameter distance which takes value of "longest_distances_via_LCA"
(the default) or "shortest_distances_via_NCA":

```r
term_sim(dag, terms, method = "Sim_Resnik_edge_2005",
    control = list(distance = "shortest_distances_via_NCA"))
```

Paper link: https://doi.org/10.1145/1097047.1097051.


## Sim_Leocock_1998

It is similar as the _Sim_Resnik_edge_2005_ method, but it applies
log-transformation on the distance and the depth:

$$ \mathrm{Sim}(a, b) = 1 - \frac{\log(D_\mathrm{sp}(a, b))}{\log(2*\delta_\mathrm{max})} $$

where $2*\delta_\mathrm{max}$ can be thought as the possible maximal distance
between two terms in the DAG.

Similarly, the distance can also be the longest distance via LCA, then it is
consistent with the definition of $\delta_\mathrm{max}$ which are both based
on the longest distance.

$$ \mathrm{Sim}(a, b) = 1 - \frac{\log(\mathrm{len}_c(a, b))}{\log(2*\delta_\mathrm{max})} $$


There is a parameter distance which takes value of "longest_distances_via_LCA"
(the default) or "shortest_distances_via_NCA":

```r
term_sim(dag, terms, method = "Sim_Leocock_1998",
    control = list(distance = "shortest_distances_via_NCA"))
```

Paper link: https://ieeexplore.ieee.org/document/6287675.


## Sim_WP_1994

It is based on the depth of the LCA term $c$ and the longest distance between
term $a$ and $b$ via $c$:

$$
\begin{align*}
 \mathrm{Sim}(a, b) & = \frac{2*\delta(c)}{\mathrm{len}(c, a) + \mathrm{len}(c, b) + 2*\delta(c)} \\
   & =  \frac{2*\delta(c)}{\mathrm{len}_c(a, b) + 2*\delta(c)}
\end{align*}
$$

And it can also be written as:

$$
\begin{align*}
 \mathrm{Sim}(a, b) & = \frac{2*\delta(c)}{\delta(c) + \mathrm{len}(c, a) + \delta(c) + \mathrm{len}(c, b)} \\
   & =  \frac{2*\delta(c)}{\delta_c(a) + \delta_c(b)}
\end{align*}
$$

where in the denominator are the depth of $a$ and $b$ via $c$.

```r
term_sim(dag, terms, method = "Sim_WP_1994")
```

Paper link: https://doi.org/10.3115/981732.981751.

## Sim_Slimani_2006

It is a correction of the Sim_WP_1994 method. The correction factor for term a and b regarding to their LCA t is:

$$ \mathrm{Sim}(a, b) = \mathrm{CF}(a, b) * \mathrm{Sim}_\mathrm{WP}(a, b) $$

$$ \mathrm{CF}(a, b) = \left\{ \begin{array}{ll}
\min\{ \delta(a), \delta(b)\} - \delta(c) & \textit{a} \text{ and } \textit{b} \text{ are not in ancestor/offspring relationship} \\
\frac{1}{1 + |\delta(a) - \delta(b)|} & \textit{a} \text{ and } \textit{b} \text{ are in ancestor/offspring relationship}
\end{array} \right. $$


Paper link: https://zenodo.org/record/1075130.

## Sim_Shenoy_2012

It is a correction of the Sim_WP_1994 method. The correction factor for term a and b is:

$$  \mathrm{CF}(a, b) = \left\{ \begin{array}{ll}
1 & \textit{a} \text{ and } \textit{b} \text{ are not in ancestor/offspring relationship} \\
\exp(-\frac{\lambda * D_\mathrm{sp}(a, b)}{\delta_\mathrm{max}})) & \textit{a} \text{ and } \textit{b} \text{ are in ancestor/offspring relationship}
\end{array} \right. $$

$D_\mathrm{sp}$ can be replaced with $\mathrm{len}(a, b)$ if longest distance is used.

Paper link: https://doi.org/10.48550/arXiv.1211.4709.

There is a parameter distance which takes value of "longest_distances_via_LCA" (the default) or "shortest_distances_via_NCA":

```r
term_sim(dag, terms, method = "Sim_Leocock_1998",
    control = list(distance = "shortest_distances_via_NCA"))
```

## Sim_Pekar_2002

It is very similar to the _Sim_WP_1994_ method:

$$ \mathrm{Sim}(a, b) = \frac{\delta(c)}{\mathrm{len}(c, a) + \mathrm{len}(c, b) + \delta(c)} $$

And the relationship to $\mathrm{Sim}_\mathrm{WP}$ is:

$$ \mathrm{Sim}_\mathrm{Pekar}(a, b) = \frac{\mathrm{Sim}_\mathrm{WP}(a, b)}{2 - \mathrm{Sim}_\mathrm{WP}(a, b)} $$

Paper link: https://aclanthology.org/C02-1090/.

## Sim_Stojanovic_2001

It is purely based on the depth of term a, b and their LCA c.


$$ \mathrm{Sim}(a, b) = \frac{\delta(c)}{\delta(a) + \delta(b) - \delta(c)} $$

Since the similarity value might be negative because there is no restrction that the path from root to a or b must pass c.

Paper link: https://doi.org/10.1145/500737.500762.

## Sim_Wang_edge_2012

It is calculated as:

$$ 
\begin{align*}
\mathrm{Sim}(a, b) & = \frac{\mathrm{len}(r, c)^2}{\mathrm{len}_c(r, a)*\mathrm{len}_c(r, b)} \\ 
   & = \frac{\delta(c)^2}{\delta_c(a)*\delta_c(b)}
\end{align*}
$$

Paper link: https://doi.org/10.1186/1477-5956-10-s1-s18.

## Sim_Zhong_2002

For a term x, it first calculates a "mile-stone" value as

$$ m(x) = 2^{-\delta(x) - 1} $$

The the distance bewteen term a and b via LCA term c is:

$$ 
\begin{align*}
D(a, b) & = D(c, a) + D(c, b) \\
   & = m(c) - m(a) + m(c) + m(b) \\
   & = 2^{-\delta(c)} - 2^{-\delta(a) - 1} - 2^{-\delta(b) - 1}
\end{align*}
$$

We can change original $\delta(a)$ and $\delta(b)$ to $\delta_c(a)$
and $\delta_c(b)$ to require the depth to reach $a$ and $b$ should go through $c$. Then above
equation becomes


$$ 
\begin{align*}
D(a, b) & = 2^{-\delta(c)} - 2^{-\delta_c(a) - 1} - 2^{-\delta_c(b) - 1} \\
    & = 2^{-\delta(c)} - 2^{-\delta(c)-\mathrm{len}(c,a)-1} - 2^{-\delta(c)-\mathrm{len}(c,b)-1} \\
    & = 2^{-\delta(c)} \left( 1 - 2^{-\mathrm{len}(c,a)-1} - 2^{-\mathrm{len}(c,b)-1} \right)
\end{align*}
$$

Then when $a = b$, $D(a, b) = 0$ and when $c = r$ and $\mathrm{len}(r, a) \to \infty$, $\mathrm{len}(r, b) \to \infty$, $D(a, b)$ reaches maximal 1. So the similarity 

$$ \mathrm{Sim}(a, b) = 1 - D(a, b)$$

ranges between 0 and 1.

Paper link: https://doi.org/10.1007/3-540-45483-7_8.

```r
term_sim(dag, terms, method = "Sim_Zhong_2002")
```

## Sim_AlMubaid_2006

It also takes accout of the distance between term a and b, and the depth of the LCA term c in the DAG. The distance is calculated as:

$$ D(a, b) = \log(1 + D_\mathrm{sp}(a, b)*(\sigma_\mathrm{max} - \sigma(c))) $$

To scale $D(a, b)$ into the range of (0, 1), the smallest value is zero when $a = b$ and 
the largest value is when $D_\mathrm{sp}(a, b)$ reach possible maximal which is $2*\delta_\mathrm{max}$

Then we can define the maximal as

$$ D_\mathrm{max} = \log(1 + 2*\delta_\mathrm{max} * \delta_\mathrm{max}) $$

And the similarity is:

$$ \mathrm{Sim}(a, b) = 1 - D(a, b)/D_max $$

Paper link: https://doi.org/10.1109/IEMBS.2006.259235.

There is a parameter distance which takes value of "longest_distances_via_LCA" (the default) or "shortest_distances_via_CA":

term_sim(dag, terms, method = "Sim_AlMubaid_2006",
    control = list(distance = "shortest_distances_via_CA"))

## Sim_Li_2003
It is similar to the Sim_AlMubaid_2006 method, but uses a non-linear form:

$$ \mathrm{Sim}(a, b) = \exp(-0.2*D_\mathrm{sp}(a, b)) * \tanh(0.6*\delta(c)) $$



Paper link: https://doi.org/10.1109/TKDE.2003.1209005.

There is a parameter distance which takes value of "longest_distances_via_LCA" (the default) or "shortest_distances_via_CA":

term_sim(dag, terms, method = "Sim_Li_2003",
    control = list(distance = "shortest_distances_via_CA"))

# Hybrid methods

Hybrid methods use both DAG structure information and IC.

## Sim_RSS_2013

The similarity is adjusted by the positions of term a, b and the LCA term c in the DAG. The similarity is defined as:

$$ \mathrm{Sim}(a, b) = \frac{\delta_\mathrm{max}}{\delta_\mathrm{max} + D_\mathrm{sp}(a, b)} * \frac{\alpha}{\alpha + \beta} $$

where d(a, b) is the distance between a and b which can be the shortest distance or the longest distance via LCA.

$$
\begin{align*}
\alpha & = \delta(c) \\
\beta & = \min\{ \eta(a), \eta(b) \}
\end{align*}
$$

In the tuning factor, alpha is the distance of LCA to root, which is depth(c). beta is the distance to leaves, which is the minimal distance (or the minimal height) of term a and b:

Similarity is set to zero if one of $a$ and $b$ is root.

Paper link: https://doi.org/10.1371/journal.pone.0066745.

There is a parameter distance which takes value of "longest_distances_via_LCA" (the default) or "shortest_distances_via_CA":

term_sim(dag, terms, method = "Sim_RSS_2013",
    control = list(distance = "shortest_distances_via_CA"))

## Sim_HRSS_2013

It is similar as the Sim_RSS_2013 method, but it uses information content instead of the distance to adjust the similarity.

It first defines the semantic distance between term a and b as the sum of the distance to their MICA term c:

$$ D(a, b) = D(c, a) + D(c, b) $$

And the distance between an ancestor to a term is:

$$ 
\begin{align*}
D(c, a) & = \mathrm{IC}(a) - \mathrm{IC}(c) \\
D(a, b) & = D(c, a) + D(c, b) = \mathrm{IC}(a) + \mathrm{IC}(b) - 2*\mathrm{IC}(c)
\end{align*}
$$

Similarly, the similarity is also corrected by the position of MICA term and a and b in the DAG:

$$ \mathrm{Sim}(a, b) = \frac{1}{1 + D(a, b)} * \frac{\alpha}{\alpha + \beta} $$

where

$$ \alpha = \mathrm{IC}(c) $$

And beta is the average of the maximal semantic distance of a and b to leaves.

$$ \beta = \frac{D(a, l_a) + D(b, l_b)}{2} = \frac{\mathrm{IC}(l_a) - \mathrm{IC}(a) + \mathrm{IC}(l_b) - \mathrm{IC}(b)}{2} $$

where $l_a$ is the leaf that a can reach with the highest IC (i.e. most informative leaf), and so is l_b.

$$ \mathrm{IC}(l_a) = \max_{z \in \mathcal{L}(a)} \mathrm{IC}(z) $$

Paper link: https://doi.org/10.1371/journal.pone.0066745.

## Sim_Shen_2010

It is based on the information content of terms on the path connecting term a and b via their MICA term c.

Denote a list of terms a, ..., c, ..., b which are composed by the shortest path from a to c and from b to c, the difference between a and b is the sum of 1/IC of the terms on the path:

Denote $S_c(a, b)$ as the set of terms on the shortest path connecting $a$ and $b$ via the MICA term $c$

The distance

$$ \mathrm{Sim}(a, b) = 1 - \frac{\tanh \left( \sum\limits_{x \in S_c(a, b)} \frac{1}{\mathrm{IC}(x)} \right)}{\pi/2} $$


Paper link: https://doi.org/10.1109/BIBM.2010.5706623.

## Sim_SSDD_2013

It is similar as the Sim_Shen_2010 which also sums content along the path passing through LCA term. Instead of summing the information content, the Sim_SSDD_2013 sums up a so-called "T-value":

sim = 1 - atan(sum_{x in the path}(T(x)))/(pi/2)
Each term has a T-value and it measures the semantic content a term averagely inherited from its parents and distributed to its offsprings. The T-value of root is 1. Assume a term t has two parents p1 and p1, The T-value for term t is averaged from its

(w1*T(p1) + w2*T(p2))/2
Since the parent may have other child terms, a factor w1 or w2 is multiplied to T(p1) and T(p2). Taking p1 as an example, it has n_p offsprings (including itself) and t has n_t offsprings (including itself), this means n_t/n_p of information is transmitted from p1 to downstream via t, thus w1 is defined as n_t/n_p.

Paper link: https://doi.org/10.1016/j.ygeno.2013.04.010.

## Sim_Jiang_1997
First semantic distance between term a and b via MICA term c is defined as:

$$ D(a, b) = IC(a) + IC(b) - 2*IC(c) $$ 

Then there are several normalization method to change the distance to similarity and to scale it into the range of [0, 1].

max: $1 - D(a, b)/2/IC_max$

Couto: $min(1, D(a, b)/IC_max)$

Lin: $1 - D(a, b)/(IC(a) + IC(b))$ which is the same as the Sim_Lin_1998 method

Garla: $1 - log(D(a, b) + 1)/log(2*IC_max + 1)$

log-Lin: $1 - log(D(a, b) + 1)/log(IC(a) + IC(b) + 1)$

Rada: $1/(1 + D(a, b))$

Paper link: https://aclanthology.org/O97-1002/.

There is a parameter norm_method which takes value in "max", "Couto", "Lin", "Carla", "log-Lin", "Rada":

term_sim(dag, terms, method = "Sim_Jiang_1997",
    control = list(norm_method = "Lin"))

# Annotation-count based methods

Denote $A$ and $B$ as the sets of the items annotated to term $a$ and $b$, and $U$ as the universe set
of all items annotated to DAG.

## Sim_Kappa

The definition of kappa coeffient is a little bit complex. First let's format the two sets
into a contigency table:

<style>
table {
  border-collapse: collapse;
}
table, th, td {
  border: 1px solid black;
}
th, td {
    padding: 2px 5px;
}
.symbol {
    font-family: Times;
    font-style: italic;
}
</style>
<center>
<table>
    <tr><td rowspan='2' colspan='2'></td><td colspan='2'>In set <b>B</b></td></tr>
    <tr><td>Yes</td><td>No</td></tr>
    <tr><td rowspan='2'>In set <b>A</b></td><td>Yes</td><td class="symbol">a</td><td class="symbol">b</td></tr>
    <tr><td>No</td><td class="symbol">c</td><td class="symbol">d</td></tr>
</table>
</center>

where $a$, $b$, $c$, $d$ are the numbers of genes that fall in each category.

Let's calculate $p_\mathrm{obs}$ and $p_\mathrm{exp}$ as: 

$$
\begin{align*}
p_\mathrm{obs} & = \frac{a+d}{a+b+c+d} \\
p_\mathrm{Yes} & = \frac{a+b}{a+b+c+d} * \frac{a+c}{a+b+c+d} \\
p_\mathrm{No} & = \frac{c+d}{a+b+c+d} * \frac{b+d}{a+b+c+d} \\
p_\mathrm{exp} & = p_\mathrm{Yes} + p_\mathrm{No}
\end{align*}
$$

where $p_\mathrm{obs}$ is the probability of a gene in both gene sets or neither in the two sets,
$p_\mathrm{Yes}$ is the probability of a gene in both gene sets by random (by assuming the events of a gene in set $A$ and set $B$ are independent), $p_\mathrm{No}$ is the probability of a gene
not in the two sets by random, and $p_\mathrm{exp}$ is the probability of a gene either both in 
the two sets or not in the two sets by random.

and the kappa coeffcient is calculated as:

$$ \mathrm{Sim}(a, b) = \frac{p_\mathrm{obs} - p_\mathrm{exp}}{1 - p_\mathrm{exp}}$$

term_sim(dag, terms, method = "Sim_kappa",
    control = list(anno_universe = ...))

## Sim_Jaccard
The similarity value is the Jaccard coeffcient of the two sets, defined as 

$$ \mathrm{Sim}(a, b) = \frac{|A \cap B|}{|A \cup B|} $$

The universe or the background can be set via parameter anno_universe:

term_sim(dag, terms, method = "Sim_Jaccard",
    control = list(anno_universe = ...))

## Sim_Dice
Denote two sets A and B as the items annotated to term a and b. The similarity value is the Dice coeffcient of the two sets, defined as 

$$ \mathrm{Sim}(a, b) = \frac{2*|A \cap B|}{|A| + |B|} $$


The universe or the background can be set via parameter anno_universe:

term_sim(dag, terms, method = "Sim_Dice",
    control = list(anno_universe = ...))

## Sim_Overlap
Denote two sets A and B as the items annotated to term a and b. The similarity value is the overlap coeffcient of the two sets, defined as.

$$ \mathrm{Sim}(a, b) = \frac{|A \cap B|}{min\{|A|, |B|\}} $$


The universe or the background can be set via parameter anno_universe:

term_sim(dag, terms, method = "Sim_Overlap",
    control = list(anno_universe = ...))

## Comparisons
