---
title: "Group similarity"
author: "Zuguang Gu ( z.gu@dkfz.de )"
date: '`r Sys.Date()`'
output: html_document
vignette: >
  %\VignetteIndexEntry{5. Group similarity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align = "center")
```


GroupSim_pairwise_avg
Denote S(a, b) as the semantic similarity between terms a and b where a is from group1 and b is from group2, The similarity between group1 and group2 is the average similarity of every pair of individual terms in the two groups:

group_sim = mean_{a in group1, b in group2}(S(a, b))
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_max
This is the maximal S(a, b) among all pairs of terms in group1 and group2:

group_sim = max_{a in group1, b in group2}(S(a, b))
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_BMA
BMA stands for "best-match average". First define similarity of a term to a group of terms as

S(x, group) = max_{y in group}(x, y)
which is the most similar terms in group to x.

Then the BMA similarity is calculated as:

group_sim = 0.5*(mean_{a in group1}(S(a, group2)) + mean_{b in group2}(S(b, group1)))
So it is the average of the similarity of every term in group1 to the whole group2 and every term in group2 to the whole group1.

The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_BMM
BMM stands for "best-match max". It is defined as:

group_sim = max(mean_{a in group1}(S(a, group2)), mean_{b in group2}(S(b, group1)))
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_ABM
ABM stands for "average best-match". It is defined as:

group_sim = (sum_{a in group1}(S(a, group2)) + sum_{b in group2}(S(b, group1)))/(n1 + n2)
where n1 and n2 are the number of terms in group1 and group2.

The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_HDF
First define the distance of a term to a group of terms:

D(x, group) = 1 - S(x, group)
Then the Hausdorff distance between two groups are:

HDF = max(max_{a in group1}(D(a, group2)), max_{b in group2}(D(b, group1)))
This final similarity is:

group_sim = 1 - HDF
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_MHDF
Instead of using the maximal distance from a group to the other group, MHDF uses mean distance:

MHDF = max(mean_{a in group1}(D(a, group2)), mean_{b in group2}(D(b, group1)))
This final similarity is:

group_sim = 1 - MHDF
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_VHDF
It is defined as:

VHDF = 0.5*(sqrt(mean_{a in group1}(D(a, group2)^2)) + sqrt(mean_{b in group2}(D(b, group1)^2)))
group_sim = 1 - VHDF
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_Froehlich_2007
The similarity is:

group_sim = exp(-HDF(group1, group2))
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_pairwise_Joeng_2014
Similar to VHDF, but it directly uses the similarity:

group_sim = 0.5*(sqrt(mean_{a in group1}(S(a, group2)^2)) + sqrt(mean_{b in group2}(S(b, group1)^2)))
The term semantic similarity method can be set via control = list(term_sim_method = ...).

GroupSim_SimALN
It is based on the average distances between every pair of terms in the two groups:

exp(-mean_{a in group1, b in group2}(d(a, b)))
d(a, b) is the distance between a and b, which can be the shortest distance between the two terms or the longest distnace via LCA.

Distance method can be set via control = list(distance = ...).

GroupSim_SimINT
To be added.

GroupSim_spgk
To be added.

GroupSim_SimGIC
Denote A and B as the two sets of ancestors terms of terms in group1 and group2 respectively, the SimGIC is:

group_sim = sum_{x in intersect(A, B)}(IC(x))/sum_{x in union(A, B)}(IC(x))
IC method can be set via control = list(IC_method = ...).

GroupSim_SimDIC
Similar as GroupSim_SimGIC, it calculates the Dice coeffcient:

group_sim = 2*sum_{x in intersect(A, B)}(IC(x))/(sum_{x in A}(IC(x)) + sum_{x in B}(IC(x)))
IC method can be set via control = list(IC_method = ...).

GroupSim_SimUIC
Similar as GroupSim_SimGIC, it is calculated as:

group_sim = sum_{x in intersect(A, B)}(IC(x))/max(sum_{x in A}(IC(x)), sum_{x in B}(IC(x)))
IC method can be set via control = list(IC_method = ...).

GroupSim_SimUI
It is only based on the number of terms. A is the set of all ancestors of group1 terms and B is the set of all ancestors of group2 terms.

group_sim = length(intersect(A, B))/length(union(A, B))
GroupSim_SimDB
It is:

group_sim = 2*length(intersect(A, B))/(length(A) + length(B))
GroupSim_SimUB
It is:

group_sim = length(intersect(A, B))/max(length(A), length(B))
GroupSim_SimNTO
It is:

group_sim = length(intersect(A, B))/min(length(A), length(B))
GroupSim_SimCOU
It is based on the dot product of two vectors p and q which correspond to terms in group1 and group2. p and q have the same length as the total number of terms. Value of position i in p or q corresponds to term t. The value takes IC(t) if t is an ancestor of any term in p or q, and the value takes zero if t is not. The similarity betweem group1 terms and group2 terms is calculated as:

<p,q>/||p||/||q||
where ⁠<p,q>⁠ is the dot product between the two, and ⁠||p||⁠ or ⁠||q||⁠ is the norm of the vector. The equation can be written as:

group_sim = sum_{x in intersect(A, B)}(IC(x)^2) / 
              sqrt(sum_{x in A}(IC(x)^2)) / 
              sqrt(sum_{x in B}(IC(x)^2))
IC method can be set via control = list(IC_method = ...).

GroupSim_SimCOT
Similar as GroupSim_SimCOU, the similarity is:

<p,q>/(||p||^2 + ||q||^2 - <p,q>)
And it can be rewritten as:

group_sim = sum_{x in intersect(A, B)}(IC(x)^2) /
    (sum_{x in A}(IC(x)^2) + sum_{x in B}(IC(x)^2) - sum_{x in intersect(A, B)}(IC(x)^2))
IC method can be set via control = list(IC_method = ...).

GroupSim_SimLP
It is the longest depth for the terms in intersect(A, B).

group_sim = max(depth(intersect(A, B)))
GroupSim_Ye_2005
It is a normalized version of GroupSim_SimLP:

group_sim = max(depth(intersect(A, B)))/max_depth
Since the minimal depth is zero for root.

GroupSim_SimCHO
It is based on the annotated items. Denote sigma(t) as the total annotated items of t. The similarity is calculated as

group_sim = log(C/sigma_max)/log(sigma_min/sigma_max)
where C is ⁠min(sigma_{x in intersect(A, B)}(x))⁠, i.e., the minimal sigma in the intersection of group1 and group2. Note Now A and B are just two sets of terms in group1 and group2. sigma_max is the total number of items annotated to the DAG, sig_min is the minimal number of items annotated to a term, which is mostly 1.

GroupSim_SimALD
A and B are just two sets of terms in group1 and group2. The similarity is calculated as:

group_sim = max_{t in intersect(A, B)}(1 - sigma(t)/N)
GroupSim_Jaccard
Say A is the set of items annotated to terms in group1 and B is the set of items annotated to group2. This is the Jaccard coeffcient between two sets.

The universe/background can be set via control = list(universe = ...).

GroupSim_Dice
It is the Dice coeffcient between A and B.

The universe/background can be set via control = list(universe = ...).

GroupSim_Overlap
It is the Overlap coeffcient between A and B.

The universe/background can be set via control = list(universe = ...).

GroupSim_Kappa
The universe/background can be set via control = list(universe = ...).